# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Keyframe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Keyframe.proto',
  package='skild',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eKeyframe.proto\x12\x05skild\"\xf0\x03\n\x08KEYFRAME\x12(\n\x07youData\x18\x01 \x01(\x0b\x32\x17.skild.KEYFRAME.YOUDATA\x12.\n\nplayerData\x18\x02 \x03(\x0b\x32\x1a.skild.KEYFRAME.PLAYERDATA\x12$\n\x05zones\x18\x03 \x03(\x0b\x32\x15.skild.KEYFRAME.ZONES\x12\"\n\x04\x62oss\x18\x04 \x01(\x0b\x32\x14.skild.KEYFRAME.BOSS\x1aS\n\x07YOUDATA\x12\x10\n\x08playerID\x18\x01 \x01(\x05\x12\x0f\n\x07playerx\x18\x02 \x01(\x05\x12\x0f\n\x07playery\x18\x03 \x01(\x05\x12\x14\n\x0cplayerColour\x18\x04 \x01(\t\x1aV\n\nPLAYERDATA\x12\x10\n\x08playerID\x18\x01 \x01(\x05\x12\x0f\n\x07playerx\x18\x02 \x01(\x05\x12\x0f\n\x07playery\x18\x03 \x01(\x05\x12\x14\n\x0cplayerColour\x18\x04 \x01(\t\x1aG\n\x05ZONES\x12\x10\n\x08zoneName\x18\x01 \x01(\t\x12\x0e\n\x06zoneID\x18\x02 \x01(\x05\x12\r\n\x05zoneX\x18\x03 \x01(\x05\x12\r\n\x05zoneY\x18\x04 \x01(\x05\x1aJ\n\x04\x42OSS\x12\x10\n\x08\x62ossName\x18\x01 \x01(\t\x12\x12\n\nbossHealth\x18\x02 \x01(\x05\x12\r\n\x05\x62ossX\x18\x03 \x01(\x05\x12\r\n\x05\x62ossY\x18\x04 \x01(\x05\x62\x06proto3')
)




_KEYFRAME_YOUDATA = _descriptor.Descriptor(
  name='YOUDATA',
  full_name='skild.KEYFRAME.YOUDATA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerID', full_name='skild.KEYFRAME.YOUDATA.playerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerx', full_name='skild.KEYFRAME.YOUDATA.playerx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playery', full_name='skild.KEYFRAME.YOUDATA.playery', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerColour', full_name='skild.KEYFRAME.YOUDATA.playerColour', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=285,
)

_KEYFRAME_PLAYERDATA = _descriptor.Descriptor(
  name='PLAYERDATA',
  full_name='skild.KEYFRAME.PLAYERDATA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerID', full_name='skild.KEYFRAME.PLAYERDATA.playerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerx', full_name='skild.KEYFRAME.PLAYERDATA.playerx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playery', full_name='skild.KEYFRAME.PLAYERDATA.playery', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerColour', full_name='skild.KEYFRAME.PLAYERDATA.playerColour', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=373,
)

_KEYFRAME_ZONES = _descriptor.Descriptor(
  name='ZONES',
  full_name='skild.KEYFRAME.ZONES',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zoneName', full_name='skild.KEYFRAME.ZONES.zoneName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoneID', full_name='skild.KEYFRAME.ZONES.zoneID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoneX', full_name='skild.KEYFRAME.ZONES.zoneX', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoneY', full_name='skild.KEYFRAME.ZONES.zoneY', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=446,
)

_KEYFRAME_BOSS = _descriptor.Descriptor(
  name='BOSS',
  full_name='skild.KEYFRAME.BOSS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bossName', full_name='skild.KEYFRAME.BOSS.bossName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bossHealth', full_name='skild.KEYFRAME.BOSS.bossHealth', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bossX', full_name='skild.KEYFRAME.BOSS.bossX', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bossY', full_name='skild.KEYFRAME.BOSS.bossY', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=522,
)

_KEYFRAME = _descriptor.Descriptor(
  name='KEYFRAME',
  full_name='skild.KEYFRAME',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='youData', full_name='skild.KEYFRAME.youData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerData', full_name='skild.KEYFRAME.playerData', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zones', full_name='skild.KEYFRAME.zones', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boss', full_name='skild.KEYFRAME.boss', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_KEYFRAME_YOUDATA, _KEYFRAME_PLAYERDATA, _KEYFRAME_ZONES, _KEYFRAME_BOSS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=522,
)

_KEYFRAME_YOUDATA.containing_type = _KEYFRAME
_KEYFRAME_PLAYERDATA.containing_type = _KEYFRAME
_KEYFRAME_ZONES.containing_type = _KEYFRAME
_KEYFRAME_BOSS.containing_type = _KEYFRAME
_KEYFRAME.fields_by_name['youData'].message_type = _KEYFRAME_YOUDATA
_KEYFRAME.fields_by_name['playerData'].message_type = _KEYFRAME_PLAYERDATA
_KEYFRAME.fields_by_name['zones'].message_type = _KEYFRAME_ZONES
_KEYFRAME.fields_by_name['boss'].message_type = _KEYFRAME_BOSS
DESCRIPTOR.message_types_by_name['KEYFRAME'] = _KEYFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KEYFRAME = _reflection.GeneratedProtocolMessageType('KEYFRAME', (_message.Message,), {

  'YOUDATA' : _reflection.GeneratedProtocolMessageType('YOUDATA', (_message.Message,), {
    'DESCRIPTOR' : _KEYFRAME_YOUDATA,
    '__module__' : 'Keyframe_pb2'
    # @@protoc_insertion_point(class_scope:skild.KEYFRAME.YOUDATA)
    })
  ,

  'PLAYERDATA' : _reflection.GeneratedProtocolMessageType('PLAYERDATA', (_message.Message,), {
    'DESCRIPTOR' : _KEYFRAME_PLAYERDATA,
    '__module__' : 'Keyframe_pb2'
    # @@protoc_insertion_point(class_scope:skild.KEYFRAME.PLAYERDATA)
    })
  ,

  'ZONES' : _reflection.GeneratedProtocolMessageType('ZONES', (_message.Message,), {
    'DESCRIPTOR' : _KEYFRAME_ZONES,
    '__module__' : 'Keyframe_pb2'
    # @@protoc_insertion_point(class_scope:skild.KEYFRAME.ZONES)
    })
  ,

  'BOSS' : _reflection.GeneratedProtocolMessageType('BOSS', (_message.Message,), {
    'DESCRIPTOR' : _KEYFRAME_BOSS,
    '__module__' : 'Keyframe_pb2'
    # @@protoc_insertion_point(class_scope:skild.KEYFRAME.BOSS)
    })
  ,
  'DESCRIPTOR' : _KEYFRAME,
  '__module__' : 'Keyframe_pb2'
  # @@protoc_insertion_point(class_scope:skild.KEYFRAME)
  })
_sym_db.RegisterMessage(KEYFRAME)
_sym_db.RegisterMessage(KEYFRAME.YOUDATA)
_sym_db.RegisterMessage(KEYFRAME.PLAYERDATA)
_sym_db.RegisterMessage(KEYFRAME.ZONES)
_sym_db.RegisterMessage(KEYFRAME.BOSS)


# @@protoc_insertion_point(module_scope)
